### ISSUE TITLE
Take screenshot again does not detect chages

### ISSUE THREAD

**Issue by fsdavid** [HumanBrainProject/interactive-viewer#482]

**Comment by xgui3783** [comment]
while this bug is no longer relevant in the current build (335a1f61e905ca89c3fdbbfaf40a8de046b7936d) added test for a related bug (ec9066a4ce5d15af003f0685bf1f3e041476c92f): hover on user landmark does not dismiss when move out of the landmark


https://user-images.githubusercontent.com/19381783/108391837-61c1ca00-7212-11eb-9bde-3d8a97eea708.mp4
