### ISSUE TITLE
[Bug] Atlas name overflowed out of the display on smaller screens

### ISSUE THREAD

**Issue by fsdavid** [HumanBrainProject/interactive-viewer#766]
![image](https://user-images.githubusercontent.com/26521731/100437970-db2d9e80-30a1-11eb-8abe-e080376ec234.png)

**Comment by xgui3783** [comment]
in the latest revision of explorer, this overflow never occurs (the atlas selector overflows instead) (see screenshot)

![Screenshot from 2021-04-14 15-09-42](https://user-images.githubusercontent.com/19381783/114715685-a01bc700-9d33-11eb-9e48-c64a8008e568.png)


I would argue this issue is now resolved.

**Comment by xgui3783** [comment]
@fsdavid can you check the current dev version if this issue is still worth addressing?

**Comment by fsdavid** [comment]
@xgui3783 Issue is resolved
